[project]
name = "build-librechat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "fastapi>=0.123.10",
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "pytest-asyncio",
    "pytest-mock>=3.15.1",
    "python-multipart>=0.0.20",
    "setuptools>=82.0.1",
    "uvicorn>=0.38.0",
    "wheel>=0.47.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "pyright>=1.1.409",
    "ruff>=0.15.12",
]
